//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria_MVC_WbyO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renta
    {
        public int Id_Renta { get; set; }
        public System.DateTime Fecha_Salida { get; set; }
        public System.DateTime Fecha_Entrega { get; set; }
        public Nullable<int> Libro_Id { get; set; }
        public Nullable<int> Cliente_Id { get; set; }
        public Nullable<int> Estado_Id { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoFisico EstadoFisico { get; set; }
        public virtual Libro Libro { get; set; }
    }
}
